# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import football_manager_pb2 as football__manager__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in football_manager_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FootballServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetClubs = channel.unary_unary(
                '/football.FootballService/GetClubs',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=football__manager__pb2.ClubList.FromString,
                _registered_method=True)
        self.GetClub = channel.unary_unary(
                '/football.FootballService/GetClub',
                request_serializer=football__manager__pb2.ClubRequest.SerializeToString,
                response_deserializer=football__manager__pb2.ClubResponse.FromString,
                _registered_method=True)


class FootballServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetClubs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClub(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FootballServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetClubs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClubs,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=football__manager__pb2.ClubList.SerializeToString,
            ),
            'GetClub': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClub,
                    request_deserializer=football__manager__pb2.ClubRequest.FromString,
                    response_serializer=football__manager__pb2.ClubResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'football.FootballService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('football.FootballService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FootballService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetClubs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/football.FootballService/GetClubs',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            football__manager__pb2.ClubList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetClub(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/football.FootballService/GetClub',
            football__manager__pb2.ClubRequest.SerializeToString,
            football__manager__pb2.ClubResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
